run:
  timeout: 1m
linters:
  enable-all: true
  disable:
    # turn on later
    - godox
    # deprecated
    - tenv
    # not relevant
    - varnamelen
    - wrapcheck
    - paralleltest
    - exhaustruct
    - dupl
linters-settings:
  lll:
    line-length: 140
  gci:
    sections:
      - Standard
      - Default
      - Prefix(github.com/gripmock)
  depguard:
    rules:
      main:
        allow:
          - $gostd
          - github.com
issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - dupl